---
- hosts: webservers 
  remote_user: root
  tasks:
   - name: "Instalacao do Apache e Mysql"
     apt: name={{ item }} state=present
     with_items:
       - apache2
       - mysql-server
       - python-pip
       - python-mysqldb   
   - name: Install the MySQL-python through pip
     sudo: yes
     pip:
       name: "{{ item }}"
       state: present 
     with_items:
       - pip3
       - MySQL-python
   - name: "Subindo o Apache e o Mysql e para que seja iniciado no boot"
     service: name={{ item }} state=started enabled=yes
     with_items:
       - apache2
       - mysql   
   - name: "Criando um DataBase de teste"
     mysql_db: name=labDB state=present   
   - name: "Criando um user para o Mysql"
     mysql_user: name=leonidas password=teste@123 priv=.:ALL state=present
